project_name: centralized-relay
env:
  - CGO_ENABLED=1
  - CC=musl-gcc
before:
  hooks:
    - ./scripts/release_hook.sh
builds:
  - id: darwin-amd64
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=musl-gcc
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags=-static -linkmode=external
      - -X github.com/icon-project/centralized-relay/v2/cmd.VERSION={{ .Tag }}
  - id: darwin-arm64
    main: ./main.go
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=musl-gcc
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags=-static -linkmode=external
      - -X github.com/icon-project/centralized-relay/v2/cmd.VERSION={{ .Tag }}
  - id: linux-amd64
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=musl-gcc
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags=-static -linkmode=external
      - -X github.com/icon-project/centralized-relay/v2/cmd.VERSION={{ .Tag }}
  - id: linux-arm64
    main: ./main.go
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=musl-gcc
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags=-static -linkmode=external
      - -X github.com/icon-project/centralized-relay/v2/cmd.VERSION={{ .Tag }}
    tags:
      - static_build
      - netgo
      - osusergo
archives:
  - id: golang-cross
    builds:
      - darwin-amd64
      - darwin-arm64
      - linux-amd64
      - linux-arm64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    wrap_in_directory: true

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

release:
  prerelease: auto
  draft: false
