services:
  relayer:
    image: icon-project/centralized-relayer:latest
    container_name: relayer
    command: ["centralized-relay", "start", "--config", "/config/config.yaml"]
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    volumes:
      - ./config:/config
      - ./data:/data
volumes:
  data:
  config:
